baseURL: "http://localhost:1313/"
title: "Luke David Fischer"
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: papers/
          weight: 2
        - name: Data Visualizations
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "Luke D. Fischer's academic fingerprint."
    author: Luke D. Fischer
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["Projects","Data Visualizations"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Luke David Fischer
          subtitle: "I am a second year research master's student in communication science at the University of Amsterdam with a background in social psychology. My academic interests lies in the study of political psychology, focusing on information processing, emotions and political participation."
          imageUrl: "profile.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Ongoing Projects
              url: papers/
            - name: Data Visualizations
              url: https://lukedfischer.github.io/RViz/


    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:lukefischer@pm.me
        - name: GitHub
          url: https://github.com/pmichaillat
        - name: Bluesky
          url: https://bsky.app/profile/pmichaillat.bsky.social
        - name: LinkedIn
          url: https://www.linkedin.com/in/luke-fischer-sep01?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Luke D. Fischer"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
